extends: default

rules:
  line-length: disable
  document-start: disable
  truthy: disable
  comments-indentation: disable
  brackets:
    max-spaces-inside: 1
  indentation:
    spaces: 2
    indent-sequences: whatever
